version: "3"
services:
  certbot:
    image: certbot/certbot:latest
    ports:
      - "80:80"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    command: |
      certonly --standalone --force-renewal --register-unsafely-without-email -d streaming.ghibranjaringan.com --agree-tos
