version: '3.5'
services:
   jellyfin:
     image: jellyfin/jellyfin
     container_name: jellyfin
     user: 1000:1000
     volumes:
       - ./config:/config
       - ./cache:/cache
       - ./media:/media
     restart: 'unless-stopped'

   transmission:
      image: lscr.io/linuxserver/transmission:latest
      container_name: transmission
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
      volumes:
        - ./transmission-data:/config
        - ./media:/downloads
      ports:
        - 51413:51413
        - 51413:51413/udp
      restart: unless-stopped
      cpus: 0.5

   nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/www:/var/www/certbot/
        - ./certbot/conf/:/etc/nginx/ssl/
        - ./.passwd:/.passwd
      ports:
        - "80:80"
        - "443:443"
      restart: 'unless-stopped'

